CREATE TABLE TEMPERATURE_SENSORS (
    ID BIGINT PRIMARY KEY AUTO INCREMENT,
    NAME VARCHAR(255) NOT NULL ,
    IS_ACTIVE BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

